<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('shops')->insert([
            [
                'id' => 1,
                'is_cafe' => true,
                'name' => 'コメダ珈琲 名古屋駅前店',
                'description' => '落ち着いた雰囲気の喫茶店。モーニングが人気です。',
                // 'address' => '愛知県名古屋市中村区名駅1-1-1',
                'address' => '愛知県西尾市中原町道東4-1',
                'phone_number' => '052-111-2222',
                'min_budget' => 500,
                'station_distance' => 150,
                'opens_at' => '08:00',
                'closes_at' => '21:00',
                'latitude' => 34.882287333456816,
                'longitude' => 137.07709153707145,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'is_cafe' => false,
                'name' => '味噌カツの矢場とん',
                'description' => '名古屋名物の味噌カツが食べられる人気店。',
                'address' => '愛知県名古屋市中区栄3-6-1',
                'phone_number' => '052-333-4444',
                'min_budget' => 1200,
                'station_distance' => 300,
                'opens_at' => '11:00',
                'closes_at' => '22:00',
                'latitude' => 35.1615,
                'longitude' => 136.9066,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'is_cafe' => true,
                'name' => 'スターバックス 名古屋ミッドランド店',
                'description' => '広々とした店内で作業にも最適なカフェ。',
                'address' => '愛知県名古屋市中村区名駅4-7-1',
                'phone_number' => '052-555-6666',
                'min_budget' => 400,
                'station_distance' => 200,
                'opens_at' => '07:00',
                'closes_at' => '22:00',
                'latitude' => 35.1699,
                'longitude' => 136.8838,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'is_cafe' => false,
                'name' => 'ひつまぶし 備長',
                'description' => '名古屋名物ひつまぶしの老舗。',
                'address' => '愛知県名古屋市中区栄3-12-4',
                'phone_number' => '052-777-8888',
                'min_budget' => 2500,
                'station_distance' => 280,
                'opens_at' => '11:30',
                'closes_at' => '21:00',
                'latitude' => 35.1677,
                'longitude' => 136.9070,
                'is_sun' => true,
                'is_mon' => false,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'is_cafe' => true,
                'name' => 'タリーズコーヒー 名古屋パルコ店',
                'description' => 'ショッピングの合間に立ち寄れるカフェ。',
                'address' => '愛知県名古屋市中区栄3-29-1',
                'phone_number' => '052-999-0000',
                'min_budget' => 350,
                'station_distance' => 220,
                'opens_at' => '08:00',
                'closes_at' => '21:30',
                'latitude' => 35.1658,
                'longitude' => 136.9026,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
