<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('shops')->insert([
            // 既存の5つ（カフェ3、その他2）
            [
                'id' => 1,
                'is_cafe' => true,
                'name' => 'コメダ珈琲 名古屋駅前店',
                'description' => '落ち着いた雰囲気の喫茶店。モーニングが人気です。',
                'address' => '愛知県西尾市中原町道東4-1',
                'phone_number' => '052-111-2222',
                'min_budget' => 500,
                'station_distance' => 150,
                'opens_at' => '08:00',
                'closes_at' => '21:00',
                'latitude' => 34.882287333456816,
                'longitude' => 137.07709153707145,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'is_cafe' => false,
                'name' => '味噌カツの矢場とん',
                'description' => '名古屋名物の味噌カツが食べられる人気店。',
                'address' => '愛知県名古屋市中区栄3-6-1',
                'phone_number' => '052-333-4444',
                'min_budget' => 1200,
                'station_distance' => 300,
                'opens_at' => '11:00',
                'closes_at' => '22:00',
                'latitude' => 35.1615,
                'longitude' => 136.9066,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'is_cafe' => true,
                'name' => 'スターバックス 名古屋ミッドランド店',
                'description' => '広々とした店内で作業にも最適なカフェ。',
                'address' => '愛知県名古屋市中村区名駅4-7-1',
                'phone_number' => '052-555-6666',
                'min_budget' => 400,
                'station_distance' => 200,
                'opens_at' => '07:00',
                'closes_at' => '22:00',
                'latitude' => 35.1699,
                'longitude' => 136.8838,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'is_cafe' => false,
                'name' => 'ひつまぶし 備長',
                'description' => '名古屋名物ひつまぶしの老舗。',
                'address' => '愛知県名古屋市中区栄3-12-4',
                'phone_number' => '052-777-8888',
                'min_budget' => 2500,
                'station_distance' => 280,
                'opens_at' => '11:30',
                'closes_at' => '21:00',
                'latitude' => 35.1677,
                'longitude' => 136.9070,
                'is_sun' => true,
                'is_mon' => false,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'is_cafe' => true,
                'name' => 'タリーズコーヒー 名古屋パルコ店',
                'description' => 'ショッピングの合間に立ち寄れるカフェ。',
                'address' => '愛知県名古屋市中区栄3-29-1',
                'phone_number' => '052-999-0000',
                'min_budget' => 350,
                'station_distance' => 220,
                'opens_at' => '08:00',
                'closes_at' => '21:30',
                'latitude' => 35.1658,
                'longitude' => 136.9026,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 追加のカフェ（id 6-22で17個、合計20個のカフェにする）
            [
                'id' => 6,
                'is_cafe' => true,
                'name' => 'ドトールコーヒー 名古屋駅店',
                'description' => '駅近で便利なカフェ。朝のコーヒーに最適。',
                'address' => '愛知県名古屋市中村区名駅1-1-4',
                'phone_number' => '052-111-1111',
                'min_budget' => 450,
                'station_distance' => 50,
                'opens_at' => '07:00',
                'closes_at' => '22:00',
                'latitude' => 35.1705,
                'longitude' => 136.8814,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'is_cafe' => true,
                'name' => 'ブルーシール 名古屋店',
                'description' => 'ハワイ発のカフェ。トロピカルな雰囲気が楽しめます。',
                'address' => '愛知県名古屋市中区錦3-15-1',
                'phone_number' => '052-222-2222',
                'min_budget' => 600,
                'station_distance' => 180,
                'opens_at' => '10:00',
                'closes_at' => '21:00',
                'latitude' => 35.1680,
                'longitude' => 136.9040,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'is_cafe' => true,
                'name' => 'カフェ・ド・クリエ 名古屋店',
                'description' => 'アートな空間でくつろげるカフェ。',
                'address' => '愛知県名古屋市中区栄2-3-1',
                'phone_number' => '052-333-3333',
                'min_budget' => 550,
                'station_distance' => 250,
                'opens_at' => '09:00',
                'closes_at' => '20:00',
                'latitude' => 35.1630,
                'longitude' => 136.9080,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'is_cafe' => true,
                'name' => 'エクセルシオール カフェ 名古屋',
                'description' => '本格的なエスプレッソが楽しめるカフェ。',
                'address' => '愛知県名古屋市中区錦3-20-1',
                'phone_number' => '052-444-4444',
                'min_budget' => 500,
                'station_distance' => 200,
                'opens_at' => '08:30',
                'closes_at' => '21:00',
                'latitude' => 35.1660,
                'longitude' => 136.9050,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'is_cafe' => true,
                'name' => 'カフェ・ベローチェ 名古屋駅前店',
                'description' => 'イタリアンカフェ。本格的なカプチーノが自慢。',
                'address' => '愛知県名古屋市中村区名駅1-1-1',
                'phone_number' => '052-555-5555',
                'min_budget' => 480,
                'station_distance' => 100,
                'opens_at' => '07:30',
                'closes_at' => '22:00',
                'latitude' => 35.1710,
                'longitude' => 136.8820,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'is_cafe' => true,
                'name' => '上島珈琲店 名古屋店',
                'description' => '老舗のコーヒー店。深い味わいのコーヒーが楽しめます。',
                'address' => '愛知県名古屋市中区錦3-18-1',
                'phone_number' => '052-666-6666',
                'min_budget' => 400,
                'station_distance' => 220,
                'opens_at' => '08:00',
                'closes_at' => '20:30',
                'latitude' => 35.1640,
                'longitude' => 136.9060,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'is_cafe' => true,
                'name' => 'カフェ・ラ・テール 名古屋',
                'description' => 'フレンチスタイルのカフェ。エレガントな空間。',
                'address' => '愛知県名古屋市中区栄2-4-1',
                'phone_number' => '052-777-7777',
                'min_budget' => 650,
                'station_distance' => 280,
                'opens_at' => '09:00',
                'closes_at' => '21:00',
                'latitude' => 35.1620,
                'longitude' => 136.9090,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'is_cafe' => true,
                'name' => 'カフェ・ド・パリ 名古屋',
                'description' => 'パリの雰囲気を味わえるカフェ。',
                'address' => '愛知県名古屋市中区錦3-22-1',
                'phone_number' => '052-888-8888',
                'min_budget' => 580,
                'station_distance' => 190,
                'opens_at' => '08:00',
                'closes_at' => '20:00',
                'latitude' => 35.1650,
                'longitude' => 136.9040,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'is_cafe' => true,
                'name' => 'カフェ・モカ 名古屋店',
                'description' => 'モカコーヒー専門店。香り高いコーヒーが自慢。',
                'address' => '愛知県名古屋市中区栄3-5-1',
                'phone_number' => '052-999-9999',
                'min_budget' => 520,
                'station_distance' => 260,
                'opens_at' => '08:30',
                'closes_at' => '21:30',
                'latitude' => 35.1600,
                'longitude' => 136.9070,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'is_cafe' => true,
                'name' => 'カフェ・ルノアール 名古屋',
                'description' => '落ち着いた雰囲気で読書や作業に最適。',
                'address' => '愛知県名古屋市中区錦3-16-1',
                'phone_number' => '052-101-0101',
                'min_budget' => 470,
                'station_distance' => 210,
                'opens_at' => '09:00',
                'closes_at' => '22:00',
                'latitude' => 35.1670,
                'longitude' => 136.9030,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'is_cafe' => true,
                'name' => 'カフェ・アマゾン 名古屋店',
                'description' => '南米のコーヒー豆を使用したカフェ。',
                'address' => '愛知県名古屋市中区栄2-6-1',
                'phone_number' => '052-202-0202',
                'min_budget' => 540,
                'station_distance' => 240,
                'opens_at' => '08:00',
                'closes_at' => '20:30',
                'latitude' => 35.1610,
                'longitude' => 136.9100,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'is_cafe' => true,
                'name' => 'カフェ・エスプレッソ 名古屋',
                'description' => '本格的なエスプレッソが楽しめるカフェ。',
                'address' => '愛知県名古屋市中区錦3-24-1',
                'phone_number' => '052-303-0303',
                'min_budget' => 510,
                'station_distance' => 170,
                'opens_at' => '07:30',
                'closes_at' => '21:00',
                'latitude' => 35.1630,
                'longitude' => 136.9050,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'is_cafe' => true,
                'name' => 'カフェ・ラッテ 名古屋店',
                'description' => 'ラテアートが美しいカフェ。',
                'address' => '愛知県名古屋市中区栄3-8-1',
                'phone_number' => '052-404-0404',
                'min_budget' => 560,
                'station_distance' => 230,
                'opens_at' => '09:00',
                'closes_at' => '21:30',
                'latitude' => 35.1590,
                'longitude' => 136.9080,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'is_cafe' => true,
                'name' => 'カフェ・マキアート 名古屋',
                'description' => 'イタリアンスタイルのカフェ。',
                'address' => '愛知県名古屋市中区錦3-19-1',
                'phone_number' => '052-505-0505',
                'min_budget' => 530,
                'station_distance' => 160,
                'opens_at' => '08:00',
                'closes_at' => '20:00',
                'latitude' => 35.1680,
                'longitude' => 136.9020,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'is_cafe' => true,
                'name' => 'カフェ・カプチーノ 名古屋店',
                'description' => 'ふわふわのカプチーノが自慢のカフェ。',
                'address' => '愛知県名古屋市中区栄2-7-1',
                'phone_number' => '052-606-0606',
                'min_budget' => 490,
                'station_distance' => 270,
                'opens_at' => '08:30',
                'closes_at' => '22:00',
                'latitude' => 35.1600,
                'longitude' => 136.9110,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'is_cafe' => true,
                'name' => 'カフェ・フラッペ 名古屋',
                'description' => '冷たいドリンクが充実したカフェ。',
                'address' => '愛知県名古屋市中区錦3-21-1',
                'phone_number' => '052-707-0707',
                'min_budget' => 460,
                'station_distance' => 140,
                'opens_at' => '10:00',
                'closes_at' => '21:00',
                'latitude' => 35.1660,
                'longitude' => 136.9010,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'is_cafe' => true,
                'name' => 'カフェ・モーニング 名古屋店',
                'description' => 'モーニングセットが充実したカフェ。',
                'address' => '愛知県名古屋市中区栄3-9-1',
                'phone_number' => '052-808-0808',
                'min_budget' => 420,
                'station_distance' => 250,
                'opens_at' => '07:00',
                'closes_at' => '20:30',
                'latitude' => 35.1580,
                'longitude' => 136.9090,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 追加のその他（id 23-40で18個、合計20個のその他にする）
            [
                'id' => 23,
                'is_cafe' => false,
                'name' => '天下一品 名古屋店',
                'description' => '濃厚なスープが自慢のラーメン店。',
                'address' => '愛知県名古屋市中区錦3-17-1',
                'phone_number' => '052-909-0909',
                'min_budget' => 800,
                'station_distance' => 180,
                'opens_at' => '11:00',
                'closes_at' => '23:00',
                'latitude' => 35.1690,
                'longitude' => 136.9040,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'is_cafe' => false,
                'name' => '一風堂 名古屋店',
                'description' => '博多ラーメンの名店。',
                'address' => '愛知県名古屋市中区栄2-5-1',
                'phone_number' => '052-010-1010',
                'min_budget' => 900,
                'station_distance' => 220,
                'opens_at' => '11:30',
                'closes_at' => '22:30',
                'latitude' => 35.1620,
                'longitude' => 136.9100,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'is_cafe' => false,
                'name' => 'すし善 名古屋店',
                'description' => '新鮮なネタが自慢の寿司店。',
                'address' => '愛知県名古屋市中区錦3-23-1',
                'phone_number' => '052-111-1112',
                'min_budget' => 3000,
                'station_distance' => 190,
                'opens_at' => '17:00',
                'closes_at' => '23:00',
                'latitude' => 35.1640,
                'longitude' => 136.9050,
                'is_sun' => true,
                'is_mon' => false,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'is_cafe' => false,
                'name' => '鳥開 名古屋店',
                'description' => '名古屋コーチンの親子丼が自慢。',
                'address' => '愛知県名古屋市中区栄3-7-1',
                'phone_number' => '052-222-2223',
                'min_budget' => 1500,
                'station_distance' => 260,
                'opens_at' => '11:00',
                'closes_at' => '22:00',
                'latitude' => 35.1600,
                'longitude' => 136.9080,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'is_cafe' => false,
                'name' => '世界の山ちゃん 名古屋店',
                'description' => '名古屋名物手羽先の名店。',
                'address' => '愛知県名古屋市中区錦3-20-1',
                'phone_number' => '052-333-3334',
                'min_budget' => 2000,
                'station_distance' => 200,
                'opens_at' => '17:00',
                'closes_at' => '23:30',
                'latitude' => 35.1650,
                'longitude' => 136.9030,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'is_cafe' => false,
                'name' => 'きしめん よしだ 名古屋店',
                'description' => '名古屋名物きしめんの老舗。',
                'address' => '愛知県名古屋市中区栄2-8-1',
                'phone_number' => '052-444-4445',
                'min_budget' => 700,
                'station_distance' => 240,
                'opens_at' => '11:00',
                'closes_at' => '21:00',
                'latitude' => 35.1610,
                'longitude' => 136.9110,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'is_cafe' => false,
                'name' => 'うなぎ 四代目 菊川 名古屋店',
                'description' => '名古屋名物うなぎの老舗。',
                'address' => '愛知県名古屋市中区錦3-18-1',
                'phone_number' => '052-555-5556',
                'min_budget' => 3500,
                'station_distance' => 170,
                'opens_at' => '11:30',
                'closes_at' => '21:30',
                'latitude' => 35.1670,
                'longitude' => 136.9020,
                'is_sun' => true,
                'is_mon' => false,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'is_cafe' => false,
                'name' => 'とんかつ 矢場とん 名古屋店',
                'description' => '名古屋名物とんかつ専門店。',
                'address' => '愛知県名古屋市中区栄3-10-1',
                'phone_number' => '052-666-6667',
                'min_budget' => 1800,
                'station_distance' => 230,
                'opens_at' => '11:00',
                'closes_at' => '22:00',
                'latitude' => 35.1590,
                'longitude' => 136.9090,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'is_cafe' => false,
                'name' => '天下一品 名古屋駅前店',
                'description' => '濃厚スープのラーメン店。',
                'address' => '愛知県名古屋市中村区名駅1-1-2',
                'phone_number' => '052-777-7778',
                'min_budget' => 850,
                'station_distance' => 80,
                'opens_at' => '11:00',
                'closes_at' => '23:00',
                'latitude' => 35.1700,
                'longitude' => 136.8810,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'is_cafe' => false,
                'name' => '焼肉 牛角 名古屋店',
                'description' => '本格的な焼肉が楽しめる店。',
                'address' => '愛知県名古屋市中区錦3-19-1',
                'phone_number' => '052-888-8889',
                'min_budget' => 2500,
                'station_distance' => 160,
                'opens_at' => '17:00',
                'closes_at' => '23:00',
                'latitude' => 35.1680,
                'longitude' => 136.9010,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'is_cafe' => false,
                'name' => '居酒屋 魚民 名古屋店',
                'description' => 'リーズナブルな居酒屋。',
                'address' => '愛知県名古屋市中区栄2-9-1',
                'phone_number' => '052-999-9990',
                'min_budget' => 3000,
                'station_distance' => 270,
                'opens_at' => '17:00',
                'closes_at' => '23:30',
                'latitude' => 35.1600,
                'longitude' => 136.9120,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'is_cafe' => false,
                'name' => 'カレー ココイチ 名古屋店',
                'description' => '本格的なカレーが楽しめる店。',
                'address' => '愛知県名古屋市中区錦3-21-1',
                'phone_number' => '052-101-1011',
                'min_budget' => 600,
                'station_distance' => 140,
                'opens_at' => '11:00',
                'closes_at' => '22:00',
                'latitude' => 35.1660,
                'longitude' => 136.9000,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'is_cafe' => false,
                'name' => 'うどん はなまる 名古屋店',
                'description' => 'コシのあるうどんが自慢。',
                'address' => '愛知県名古屋市中区栄3-11-1',
                'phone_number' => '052-202-2022',
                'min_budget' => 500,
                'station_distance' => 250,
                'opens_at' => '11:00',
                'closes_at' => '21:00',
                'latitude' => 35.1580,
                'longitude' => 136.9100,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'is_cafe' => false,
                'name' => 'パスタ サイゼリヤ 名古屋店',
                'description' => 'リーズナブルなイタリアン。',
                'address' => '愛知県名古屋市中区錦3-22-1',
                'phone_number' => '052-303-3033',
                'min_budget' => 800,
                'station_distance' => 180,
                'opens_at' => '11:00',
                'closes_at' => '22:00',
                'latitude' => 35.1630,
                'longitude' => 136.9040,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'is_cafe' => false,
                'name' => '中華料理 バーミヤン 名古屋店',
                'description' => '本格的な中華料理が楽しめる店。',
                'address' => '愛知県名古屋市中区栄2-10-1',
                'phone_number' => '052-404-4044',
                'min_budget' => 1500,
                'station_distance' => 220,
                'opens_at' => '11:30',
                'closes_at' => '22:30',
                'latitude' => 35.1610,
                'longitude' => 136.9130,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'is_cafe' => false,
                'name' => 'ステーキ いきなり 名古屋店',
                'description' => '本格的なステーキが楽しめる店。',
                'address' => '愛知県名古屋市中区錦3-24-1',
                'phone_number' => '052-505-5055',
                'min_budget' => 2000,
                'station_distance' => 160,
                'opens_at' => '17:00',
                'closes_at' => '23:00',
                'latitude' => 35.1690,
                'longitude' => 136.9030,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'is_cafe' => false,
                'name' => 'お好み焼き 千房 名古屋店',
                'description' => '本格的なお好み焼きが楽しめる店。',
                'address' => '愛知県名古屋市中区栄3-12-1',
                'phone_number' => '052-606-6066',
                'min_budget' => 1200,
                'station_distance' => 240,
                'opens_at' => '11:00',
                'closes_at' => '22:00',
                'latitude' => 35.1570,
                'longitude' => 136.9110,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'is_cafe' => false,
                'name' => 'もつ鍋 一平 名古屋店',
                'description' => '名古屋名物もつ鍋の名店。',
                'address' => '愛知県名古屋市中区錦3-25-1',
                'phone_number' => '052-707-7077',
                'min_budget' => 1800,
                'station_distance' => 150,
                'opens_at' => '17:00',
                'closes_at' => '23:00',
                'latitude' => 35.1700,
                'longitude' => 136.9020,
                'is_sun' => true,
                'is_mon' => true,
                'is_tue' => true,
                'is_wed' => true,
                'is_thu' => true,
                'is_fri' => true,
                'is_sat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
