services:
  app:
    build: ./front
    volumes:
      - ./front:/frontå
    ports:
      - 3000:3000
  api:
    build: ./back
    volumes:
      - ./back:/back
    ports:
      - 8000:8000
  db:
    image: mysql:8.4
    volumes:
      - ./back/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3307:3306
